// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash32 } from "./Hash32";
import type { MmrInclusionProof } from "./MmrInclusionProof";

/**
 * Proves that a burn output is in an L1 block, against that block's `block_output_mr`.
 *
 * The block output MMR has the block's coinbase output hashes as leaves, then one last leaf: the root of the MMR of
 * every other output hash in the block (the normal output MMR). A burn is never a coinbase, so the proof has two
 * levels: the output hash in the normal output MMR, then that MMR's root as the last leaf of the block output MMR.
 */
export type BurnOutputInclusionProof = {
  block_hash: Hash32;
  normal_output_proof: MmrInclusionProof;
  normal_output_mr: Hash32;
  block_output_proof: MmrInclusionProof;
};
