// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BurnOutputFeatures } from "./BurnOutputFeatures";
import type { Hash32 } from "./Hash32";
import type { RistrettoPublicKeyBytes } from "./RistrettoPublicKeyBytes";

/**
 * The fields of an L1 burn output that its hash commits to, in hash order, less the commitment, which is
 * [`MinotariBurnClaimProof::commitment`].
 *
 * The range proof is carried as its hash, which is all the output hash commits to. `script`, `metadata_signature`,
 * `covenant` and `encrypted_data` are their L1 consensus (borsh) encodings, hashed as given and never decoded.
 */
export type BurnOutput = {
  version: number;
  features: BurnOutputFeatures;
  rangeproof_hash: Hash32;
  script: string;
  /**
   * The public nonce `R` the output was burnt with
   */
  sender_offset_public_key: RistrettoPublicKeyBytes;
  metadata_signature: string;
  covenant: string;
  encrypted_data: string;
  minimum_value_promise: number | bigint | string;
};
