// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BurnSidechainId } from "./BurnSidechainId";
import type { RistrettoPublicKeyBytes } from "./RistrettoPublicKeyBytes";

/**
 * The `OutputFeatures` of an L1 burn output that Ootle mints against.
 *
 * Only the fields that vary between such outputs are carried. The rest are fixed: the output type is `Burn`, the
 * coinbase extra is empty, and the sidechain feature is a `ConfidentialOutput` naming `claim_public_key`.
 */
export type BurnOutputFeatures = {
  version: number;
  maturity: number | bigint | string;
  /**
   * The stealth key `S` the burn is made out to. Only its holder may claim the burn.
   */
  claim_public_key: RistrettoPublicKeyBytes;
  /**
   * The sidechain the burn is tagged for, with the deployment key's signature of `claim_public_key`. `None` is
   * the default Ootle chain.
   */
  sidechain_id: BurnSidechainId | null;
  range_proof_type: number;
};
