// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EndEpochAtom } from "./EndEpochAtom";
import type { ForeignProposalAtom } from "./ForeignProposalAtom";
import type { LocalOnlyAtom } from "./LocalOnlyAtom";
import type { TransactionAtom } from "./TransactionAtom";

export type Command =
  | { LocalOnly: LocalOnlyAtom }
  | { LocalPrepare: TransactionAtom }
  | { LocalAccept: TransactionAtom }
  | { AllAccept: TransactionAtom }
  | { SomeAccept: TransactionAtom }
  | { ForeignProposal: ForeignProposalAtom }
  | { EndEpoch: EndEpochAtom };
