// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EndEpochAtom } from "./EndEpochAtom";
import type { ForeignProposalAtom } from "./ForeignProposalAtom";
import type { LocalOnlyAtom } from "./LocalOnlyAtom";
import type { MultiShardAtom } from "./MultiShardAtom";

export type Command =
  | { LocalOnly: LocalOnlyAtom }
  | { LocalPrepare: MultiShardAtom }
  | { LocalAccept: MultiShardAtom }
  | { AllAccept: MultiShardAtom }
  | { SomeAccept: MultiShardAtom }
  | { ForeignProposal: ForeignProposalAtom }
  | { EndEpoch: EndEpochAtom };
