// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownSubstate } from "./DownSubstate";
import type { UpSubstate } from "./UpSubstate";

export type DiffSummary = {
  upped: Array<UpSubstate>;
  /**
   * The substates the transaction downed without upping a later version: spent UTXOs and
   * confidential outputs.
   *
   * A substate that is upped is always downed at its previous version, so those downs are implied
   * by `upped` and are left out to keep the receipt small.
   */
  downed: Array<DownSubstate>;
};
