// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubstateId } from "./SubstateId";
import type { SubstateVersion } from "./SubstateVersion";

export type DownSubstate = { substate_id: SubstateId; version: SubstateVersion };
