// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubstateVersion } from "./SubstateVersion";

export type EvidenceInputLockData = { is_write: boolean; version: SubstateVersion };
