// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash32 } from "./Hash32";
import type { SubstateVersion } from "./SubstateVersion";

export type EvidenceInputLockData = {
  is_write: boolean;
  version: SubstateVersion;
  /**
   * Hash of the value the input was locked on. The evidence is part of the command that the shard group's commit
   * proof covers, so this is what authenticates the value when it is pledged to another shard group.
   */
  pledged_value_hash: Hash32 | null;
};
