// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Decision } from "./Decision";
import type { LeaderFee } from "./LeaderFee";

export type LocalOnlyAtom = {
  id: string;
  decision: Decision;
  transaction_fee: bigint;
  leader_fee: LeaderFee | null;
};
