// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A collection of user-defined data used to describe other types, for example, non-fungible tokens or events.
 *
 * Values are arbitrary CBOR, each held as the exact encoding its producer wrote, so a value that goes
 * into a hashed substate comes back out byte for byte. Read one with [`Self::get_as`] for a typed
 * value or [`Self::get_str`] when it is known to be text.
 */
export type Metadata = Record<string, any>;
