// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BurnOutput } from "./BurnOutput";
import type { BurnOutputInclusionProof } from "./BurnOutputInclusionProof";
import type { PedersenCommitmentBytes } from "./PedersenCommitmentBytes";
import type { SchnorrSignatureBytes } from "./SchnorrSignatureBytes";

/**
 * Proves that an L1 burn output exists and that the claimant can open its commitment.
 *
 * The output is proven by recomputing its L1 hash from [`BurnOutput`] and folding that hash up to the
 * `block_output_mr` of the L1 header named by [`BurnOutputInclusionProof::block_hash`].
 */
export type MinotariBurnClaimProof = {
  /**
   * The commitment of the burn output
   */
  commitment: PedersenCommitmentBytes;
  ownership_proof: SchnorrSignatureBytes;
  value: number | bigint | string;
  output: BurnOutput;
  inclusion_proof: BurnOutputInclusionProof;
};
