// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash32 } from "./Hash32";

/**
 * An inclusion proof of a leaf in an L1 Merkle mountain range.
 */
export type MmrInclusionProof = {
  leaf_index: number | bigint | string;
  /**
   * The node count of the MMR the proof was made for
   */
  mmr_size: number | bigint | string;
  /**
   * The sibling hashes from the leaf up to its local peak
   */
  path: Array<Hash32>;
  /**
   * The MMR peaks, less the leaf's local peak
   */
  peaks: Array<Hash32>;
};
