// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The version of a substate: the number of times it has been written since it was created at version 0.
 *
 * Every encoding (serde, CBOR and Borsh) is that of the inner `u64`, so the version hashes, and addresses the JMT,
 * exactly as a bare integer would.
 */
export type SubstateVersion = number;
