// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash32 } from "./Hash32";
import type { SubstateId } from "./SubstateId";
import type { SubstateVersion } from "./SubstateVersion";

export type UpSubstate = { substate_id: SubstateId; version: SubstateVersion; value_hash: Hash32 };
