// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash32 } from "./Hash32";
import type { SubstateLockType } from "./SubstateLockType";
import type { VersionedSubstateId } from "./VersionedSubstateId";

export type VersionedSubstateIdLockIntent = {
  versioned_substate_id: VersionedSubstateId;
  lock_type: SubstateLockType;
  require_version: boolean;
  pledged_value_hash: Hash32 | null;
};
