// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Block } from "../Block";

export type GetBlockResponse = {
  block: Block;
  /**
   * Total WASM metering points consumed by transactions executed for this block.
   */
  total_wasm_execution_points: bigint;
  /**
   * Total native verification points charged to transactions executed for this block.
   */
  total_native_execution_points: bigint;
  /**
   * The per-block execution points budget a leader packs against. It governs the sum of the two totals above,
   * so only that sum is a meaningful proportion of it.
   */
  max_block_execution_points: bigint;
};
