// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";

export type AccountsGetFaucetBalanceResponse = {
  /**
   * The faucet's available balance.
   */
  balance: Amount;
  /**
   * The amount a single claim takes from the faucet. A claim fails while `balance` is below it.
   */
  claim_amount: Amount;
};
