// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StealthUtxosGetValueLookupInfoResponse = {
  configured: boolean;
  path: string | null;
  format: string | null;
  min: bigint | null;
  max: bigint | null;
  prefix_len: number | null;
  value_len: number | null;
  num_records: bigint | null;
};
