// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TransactionRequestCreateResponse = {
  request_id: string;
  /**
   * Hash of the frozen bytes. An approval commits to this.
   */
  transaction_hash: string;
  /**
   * Unix timestamp (seconds).
   */
  expires_at: bigint;
};
