// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TransactionRequestDecisionRequest = {
  request_id: string;
  /**
   * The hash the approver saw. When set, the request is only acted on if it
   * still hashes to this -- so a UI that rendered a stale request cannot
   * approve something other than what was displayed.
   */
  transaction_hash: string | null;
};
