// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnsignedTransaction } from "../UnsignedTransaction";
import type { KeyId } from "./KeyId";

/**
 * Create a transaction request for a separately-permissioned principal to
 * approve (issue #2343).
 *
 * The transaction is frozen at creation: inputs are detected now, the seal
 * flag is normalised now, and the resulting bytes are what an approval commits
 * to and what submit seals. Nothing may rewrite them afterwards, so
 * `detect_inputs` is honoured here rather than at submit.
 */
export type TransactionRequestCreateRequest = {
  transaction: UnsignedTransaction;
  seal_signer: KeyId;
  other_signers: Array<KeyId>;
  /**
   * Attempt to infer inputs and their dependencies from instructions. If false, the provided transaction must
   * contain the required inputs.
   */
  detect_inputs: boolean;
  /**
   * If true(default), detected inputs will omit versions allowing consensus to resolve input substates.
   */
  detect_inputs_use_unversioned: boolean;
  /**
   * Locks holding this request's inputs. Their timeouts are extended to
   * outlive the approval window. Stealth spend keys are derived from these
   * at submit -- a caller cannot name them.
   */
  lock_ids: Array<number>;
  /**
   * How long a human has to approve, in seconds. Defaults to the daemon's
   * configured window.
   */
  ttl_secs: number | null;
};
