// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The values a balance recovery actually covered, so a `None` result can be told apart from a value
 * the search never reached.
 *
 * Recovering a viewable balance is a reverse lookup over a range of candidate values, and the range
 * is not always the one the caller named: without a lookup table file the daemon caps how much of it
 * one request may scan, and with one the file's own coverage is what bounds the answer. A client that
 * only sees `None` cannot tell "this output does not hold that value" from "nobody looked there".
 */
export type ValueScanCoverage = { min: bigint; max: bigint; clamped: boolean };
