// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";
import type { Resource } from "../Resource";
import type { SubstateVersion } from "../SubstateVersion";

export type GetResourceResponse = { resource: Resource; version: SubstateVersion; total_supply: Amount | null };
