// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubstateId } from "../SubstateId";

export type GetSubstatesRequest = {
  /**
   * The list of substate IDs to fetch
   */
  requests: Array<SubstateId>;
  /**
   * If true, only search local storage for the substates. This may result in substates not being found even if they
   * exist. Otherwise, the indexer will attempt to fetch substates from validator nodes across various shard groups
   * which may result in more failures.
   */
  cached_only: boolean;
  /**
   * If true, the response carries the proof each substate was verified with. Not combinable with
   * `cached_only`.
   */
  include_proofs: boolean;
};
