// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Substate } from "../Substate";
import type { SubstateId } from "../SubstateId";
import type { SubstateProof } from "./SubstateProof";

export type GetSubstatesResponse = {
  substates: { [key in SubstateId]?: Substate };
  /**
   * The proof each substate was verified with, when `include_proofs` was set. A substate no
   * committee member could prove has no entry.
   */
  proofs: { [key in SubstateId]?: SubstateProof };
};
