// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubstateVersion } from "../SubstateVersion";

export type IndexerGetSubstateRequest = {
  version: SubstateVersion | null;
  local_search_only: boolean;
  /**
   * If true, the indexer asks the committee for the substate and returns the proof it verified the
   * answer with. Not combinable with `local_search_only`.
   */
  include_proof: boolean;
};
