// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionId } from "../TransactionId";

export type IndexerGetTransactionResultRequest = {
  /**
   * The ID of the transaction to query the result for
   */
  transaction_id: TransactionId;
  /**
   * If true, a committed transaction's result carries its receipt and the proof that the receipt
   * was committed.
   */
  include_proof: boolean;
};
