// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexerTransactionFinalizedResult } from "./IndexerTransactionFinalizedResult";
import type { ProvenTransactionReceipt } from "./ProvenTransactionReceipt";

export type IndexerGetTransactionResultResponse = {
  /**
   * The result of the transaction, which may be pending (not yet finalized) or finalized with details such as the
   * final decision, execution result, and timestamps
   */
  result: IndexerTransactionFinalizedResult;
  /**
   * The committed transaction receipt and its proof, when `include_proof` was set and the
   * transaction committed. An aborted transaction commits no receipt.
   */
  receipt?: ProvenTransactionReceipt;
};
