// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubstateVersion } from "../SubstateVersion";

export type IndexerGetSubstateRequest = { version: SubstateVersion | null; local_search_only: boolean };
