// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubstateValue } from "../SubstateValue";
import type { SubstateVersion } from "../SubstateVersion";

export type IndexerGetSubstateResponse = {
  version: SubstateVersion;
  substate: SubstateValue;
  /**
   * True when the indexer verified this substate's value against the shard group committee (via a
   * merkle proof). False when proofs are disabled, or when no committee member could supply a
   * proof yet (e.g. nothing committed since an epoch change) and the value was served unverified.
   */
  verified: boolean;
};
