// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "../Epoch";
import type { Hash32 } from "../Hash32";

export type IndexerGetEpochManagerStatsResponse = {
  /**
   * The current epoch according to the indexer's epoch oracle view
   */
  current_epoch: Epoch;
  /**
   * The epoch the validators execute transactions in, as the indexer has observed from their
   * committed blocks. It trails `current_epoch` after each epoch boundary until every committee
   * has committed its end-of-epoch block. `None` until the indexer has observed every committee.
   */
  consensus_epoch: Epoch | null;
  current_block_height: bigint;
  current_block_hash: Hash32;
};
