// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubstateValue } from "../SubstateValue";
import type { SubstateVersion } from "../SubstateVersion";

export type InspectSubstateResponse = { version: SubstateVersion; substate: SubstateValue };
