// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionId } from "../TransactionId";
import type { TransactionSource } from "./TransactionSource";

export type ListRecentTransactionsRequest = {
  limit: number | null;
  last_id: TransactionId | null;
  /**
   * Restrict the listing to transactions from this source. Omitted, transactions from every
   * source are listed.
   */
  source: TransactionSource | null;
};
