// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubstateVersion } from "../SubstateVersion";
import type { TransactionReceipt } from "../TransactionReceipt";
import type { SubstateProof } from "./SubstateProof";

/**
 * A committed transaction's receipt substate, with the proof it was verified with.
 */
export type ProvenTransactionReceipt = {
  version: SubstateVersion;
  receipt: TransactionReceipt;
  /**
   * `None` when no committee member could prove the receipt, e.g. when nothing has been committed
   * since an epoch change.
   */
  proof: SubstateProof | null;
};
