// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A burn rate the council has scheduled, taking effect from `activation_epoch`.
 */
export type ScheduledBurnRate = { activation_epoch: bigint; rate_bps: number };
