// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "../Epoch";
import type { Hash32 } from "../Hash32";
import type { ShardGroup } from "../ShardGroup";

/**
 * The committed block a [`SubstateProof`] is anchored at.
 */
export type SubstateProofAnchor = {
  epoch: Epoch;
  shard_group: ShardGroup;
  height: number;
  block_id: Hash32;
  /**
   * The shard group state root the block header commits.
   */
  state_merkle_root: Hash32;
};
