// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "../Epoch";
import type { SubstateProofAnchor } from "./SubstateProofAnchor";

/**
 * Proof that a substate value was committed by its shard group.
 *
 * Two parts: a commit proof that the shard group committee committed a block whose header carries
 * `anchor.state_merkle_root`, and a value proof that the substate's leaf is in the state tree under
 * that root. Verifying it requires the committee for `anchor.epoch` and `anchor.shard_group`.
 *
 * A proof shows the value was committed at the anchor block. It says nothing about later blocks, so
 * a caller judges freshness by the anchor's epoch and height.
 */
export type SubstateProof = {
  /**
   * The committed block the proof is anchored at, as read from `commit_proof`.
   */
  anchor: SubstateProofAnchor;
  /**
   * CBOR-encoded `SidechainBlockCommitProof`: the anchor block's header and the chain of quorum
   * certificates that committed it.
   */
  commit_proof: string;
  /**
   * CBOR-encoded `SubstateValueProof`: the inclusion proof of the substate's leaf under
   * `anchor.state_merkle_root`.
   */
  value_proof: string;
  /**
   * The epoch the substate's leaf value hash was computed in. It is an input to that hash, so a
   * verifier needs it to recompute the leaf.
   */
  value_hash_epoch: Epoch;
};
