// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidatorProbeErrorKind } from "./ValidatorProbeErrorKind";

/**
 * Why a probe of a validator produced no snapshot.
 */
export type ValidatorProbeError = { kind: ValidatorProbeErrorKind; message: string };
