// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "../Epoch";
import type { ValidatorConsensusState } from "./ValidatorConsensusState";

/**
 * A validator's consensus pacemaker state as it reported it to the indexer.
 */
export type ValidatorStatusSnapshot = {
  epoch: Epoch;
  height: bigint;
  /**
   * The validator's self-reported consensus pacemaker state. Diagnostic only - this is not
   * verified, so it should not be relied upon for anything but display.
   */
  state: ValidatorConsensusState;
  /**
   * Unix timestamp (seconds) at which this snapshot was captured.
   */
  observed_at_unix_s: bigint;
};
