// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShardGroup } from "../ShardGroup";
import type { ValidatorStatusSnapshot } from "./ValidatorStatusSnapshot";

/**
 * The latest probe of one validator's consensus pacemaker state, made by the indexer when it
 * opened a sync stream from that validator.
 */
export type ValidatorStatus = {
  /**
   * libp2p PeerId of the validator.
   */
  peer_id: string;
  shard_group: ShardGroup;
  /**
   * Unix timestamp (seconds) of the latest probe.
   */
  probed_at_unix_s: bigint;
  /**
   * Why the latest probe produced no snapshot, or `None` when it produced `snapshot`. While this
   * is set, `snapshot` is stale: it is the last one an earlier probe produced.
   */
  probe_error: string | null;
  /**
   * The last snapshot any probe of this validator produced, or `None` if none has succeeded.
   */
  snapshot: ValidatorStatusSnapshot | null;
};
